name: Build and Upload APK & IPA

on:
  push:
    branches:
      - main  # Runs on every push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set up Java and Android SDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Set up Fastlane for iOS
        run: |
          cd ios
          gem install fastlane
          fastlane init

      - name: Build iOS App
        run: |
          cd ios
          fastlane gym --export_method ad-hoc

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ipa
          path: ios/build/*.ipa
