name: Build and Upload APK & IPA

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Ensure the latest checkout version is used
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Ensure latest Node.js setup
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ✅ Install project dependencies
      - name: Install dependencies
        run: npm install

      # ✅ Set up Java & Android SDK for React Native Android build
      - name: Set up Java and Android SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # ✅ Build the Android APK
      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      # ✅ Debug APK Path to verify if APK was generated
      - name: Debug APK Path
        run: ls -al android/app/build/outputs/apk/release/

      # ✅ Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error  # Prevent silent failures

      # ✅ Set up Fastlane for iOS builds
      - name: Set up Fastlane for iOS
        run: |
          cd ios
          gem install fastlane
          fastlane init

      # ✅ Build iOS App using Fastlane
      - name: Build iOS App
        run: |
          cd ios
          fastlane gym --export_method ad-hoc

      # ✅ Debug iOS Build Path to verify IPA file exists
      - name: Debug iOS Build Path
        run: ls -al ios/build/

      # ✅ Upload IPA as an artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: ios/build/App.ipa  # Ensure this matches actual output
          if-no-files-found: error  # Prevent silent failures
